GET http://localhost:5101/api/orders

###
POST http://localhost:5101/api/orders
Content-Type: application/json

{
  "items": [
    {
      "productId": 1,
      "quantity": 2
    },
    {
      "productId": 2,
      "quantity": 2
    }
  ]
}

###
GET http://localhost:5101/api/orders/1

###
GET http://localhost:5101/api/products